spring:
  mail:
    host: smtp.gmail.com
    username: developersandy91@gmail.com
    password: ddooyngelkbnkyly
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true